name: Publish Docker image
on:
  push:
    branches: ["main", "release"]
    paths: ["VERSION"]
    tags: ["v*.*.*"]
  workflow_run:
    workflows: ["Node.js CI", "CodeQL Advanced"]
    types: [completed]
jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # -------------------------------
      # Build & push log-output image
      # -------------------------------
      - name: Extract metadata for log-output
        id: meta-log-output
        uses: docker/metadata-action@v5
        with:
          images: quangcuonghuynh/log-output
      - name: Build and push log-output image
        id: log-output-push
        uses: docker/build-push-action@v5
        with:
          context: ./log_output
          push: true
          tags: ${{ steps.meta-log-output.outputs.tags }}
          labels: ${{ steps.meta-log-output.outputs.labels }}
      - name: Attest log-output image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/quangcuonghuynh/log-output
          subject-digest: ${{ steps.log-output-push.outputs.digest }}
          push-to-registry: true
      # -------------------------------
      # Build & push todo-app image
      # -------------------------------
      - name: Extract metadata for todo-app
        id: meta-todo
        uses: docker/metadata-action@v5
        with:
          images: quangcuonghuynh/todo-app
      - name: Build and push todo-app image
        id: todo-push
        uses: docker/build-push-action@v5
        with:
          context: ./the_project/todo-app
          push: true
          tags: ${{ steps.meta-todo.outputs.tags }}
          labels: ${{ steps.meta-todo.outputs.labels }}
      - name: Attest todo-app image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/quangcuonghuynh/todo-app
          subject-digest: ${{ steps.todo-push.outputs.digest }}
          push-to-registry: true
